# .github/workflows/ci.yml
name: Cross-Platform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update -y || brew update
          sudo apt-get install -y llvm clang gcovr || brew install llvm ninja gcovr

      - name: Configure (with coverage on Linux/macOS)
        run: >
          cmake -G Ninja 
          -DENABLE_COVERAGE=${{ runner.os != 'Windows' && 'ON' || 'OFF' }}
          -DCMAKE_BUILD_TYPE=Debug 
          -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Generate coverage (Linux only)
        if: runner.os == 'Linux'
        run: |
          cd build
          llvm-profdata merge -sparse coverage.profraw -o coverage.profdata
          llvm-cov show ./run_tests \
            -instr-profile=coverage.profdata \
            -ignore-filename-regex="/usr.*" \
            -format=html \
            -output-dir coverage_html

      - name: Upload coverage report (Linux only)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage_html
